# Script de configuration pour SWALO Mobile (Windows PowerShell)
# Ce script aide à configurer l'URL de l'API automatiquement

Write-Host "🚀 Configuration de SWALO Mobile" -ForegroundColor Cyan
Write-Host "================================" -ForegroundColor Cyan
Write-Host ""

# Détection de l'adresse IP
Write-Host "📱 Détection de l'adresse IP..." -ForegroundColor Yellow

$IP = (Get-NetIPAddress -AddressFamily IPv4 |
       Where-Object { $_.InterfaceAlias -like "*Wi-Fi*" -or $_.InterfaceAlias -like "*Ethernet*" } |
       Where-Object { $_.IPAddress -notlike "127.*" -and $_.IPAddress -notlike "169.254.*" } |
       Select-Object -First 1).IPAddress

if (-not $IP) {
    Write-Host "❌ Impossible de détecter automatiquement l'adresse IP" -ForegroundColor Red
    Write-Host ""
    Write-Host "Utilisez 'ipconfig' pour trouver votre adresse IP" -ForegroundColor Yellow
    $IP = Read-Host "Entrez votre adresse IP locale"
}

Write-Host ""
Write-Host "✅ Adresse IP détectée: $IP" -ForegroundColor Green
Write-Host ""

# Demander le port de l'API
$PortInput = Read-Host "Port de l'API (défaut: 3000)"
$Port = if ($PortInput) { $PortInput } else { "3000" }

# Créer le fichier .env
$EnvFile = ".env"
Write-Host "📝 Création du fichier $EnvFile..." -ForegroundColor Yellow

$EnvContent = @"
# API Configuration
# Generated by setup.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
EXPO_PUBLIC_API_URL=http://${IP}:${Port}/api

# For production deployment, use your server's public URL:
# EXPO_PUBLIC_API_URL=https://your-domain.com/api
"@

Set-Content -Path $EnvFile -Value $EnvContent -Encoding UTF8

Write-Host "✅ Fichier .env créé avec succès!" -ForegroundColor Green
Write-Host ""

# Tester la connexion à l'API
Write-Host "🔍 Test de connexion à l'API..." -ForegroundColor Yellow
$ApiUrl = "http://${IP}:${Port}/api/health"

try {
    $Response = Invoke-WebRequest -Uri $ApiUrl -Method GET -TimeoutSec 5 -ErrorAction Stop
    if ($Response.StatusCode -eq 200) {
        Write-Host "✅ L'API est accessible à $ApiUrl" -ForegroundColor Green
    }
} catch {
    Write-Host "⚠️  L'API ne répond pas" -ForegroundColor Yellow
    Write-Host "   Assurez-vous que l'API est démarrée:" -ForegroundColor Yellow
    Write-Host "   docker-compose up -d" -ForegroundColor White
}

Write-Host ""
Write-Host "🎉 Configuration terminée!" -ForegroundColor Green
Write-Host ""
Write-Host "Prochaines étapes:" -ForegroundColor Cyan
Write-Host "  1. Lancez l'application: npx expo start" -ForegroundColor White
Write-Host "  2. Scannez le QR code avec Expo Go" -ForegroundColor White
Write-Host "  3. Connectez-vous avec le code PIN 1234" -ForegroundColor White
Write-Host ""
Write-Host "Appuyez sur une touche pour continuer..." -ForegroundColor Gray
$null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
