#!/bin/bash

# Script de configuration pour SWALO Mobile
# Ce script aide à configurer l'URL de l'API automatiquement

echo "🚀 Configuration de SWALO Mobile"
echo "================================"
echo ""

# Détection du système d'exploitation
if [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS
    echo "📱 Détection de l'adresse IP (macOS)..."
    IP=$(ifconfig | grep "inet " | grep -v 127.0.0.1 | awk '{print $2}' | head -n 1)
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    # Linux
    echo "📱 Détection de l'adresse IP (Linux)..."
    IP=$(hostname -I | awk '{print $1}')
else
    # Windows (Git Bash ou WSL)
    echo "📱 Détection de l'adresse IP (Windows)..."
    IP=$(ipconfig.exe | grep "IPv4" | grep -v "127.0.0.1" | awk '{print $NF}' | tr -d '\r' | head -n 1)
fi

if [ -z "$IP" ]; then
    echo "❌ Impossible de détecter automatiquement l'adresse IP"
    echo ""
    echo "Veuillez trouver votre adresse IP manuellement:"
    echo "  - Windows: ipconfig"
    echo "  - Mac/Linux: ifconfig"
    echo ""
    read -p "Entrez votre adresse IP locale: " IP
fi

echo ""
echo "✅ Adresse IP détectée: $IP"
echo ""

# Demander le port de l'API
read -p "Port de l'API (défaut: 3000): " PORT
PORT=${PORT:-3000}

# Créer le fichier .env
ENV_FILE=".env"
echo "📝 Création du fichier $ENV_FILE..."

cat > "$ENV_FILE" << EOF
# API Configuration
# Generated by setup.sh on $(date)
EXPO_PUBLIC_API_URL=http://${IP}:${PORT}/api

# For production deployment, use your server's public URL:
# EXPO_PUBLIC_API_URL=https://your-domain.com/api
EOF

echo "✅ Fichier .env créé avec succès!"
echo ""

# Tester la connexion à l'API
echo "🔍 Test de connexion à l'API..."
API_URL="http://${IP}:${PORT}/api/health"

if command -v curl &> /dev/null; then
    RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" "$API_URL" 2>/dev/null)

    if [ "$RESPONSE" == "200" ]; then
        echo "✅ L'API est accessible à $API_URL"
    else
        echo "⚠️  L'API ne répond pas (code: $RESPONSE)"
        echo "   Assurez-vous que l'API est démarrée:"
        echo "   docker-compose up -d"
    fi
else
    echo "⚠️  curl n'est pas installé, impossible de tester la connexion"
    echo "   Vous pouvez tester manuellement: curl $API_URL"
fi

echo ""
echo "🎉 Configuration terminée!"
echo ""
echo "Prochaines étapes:"
echo "  1. Lancez l'application: npx expo start"
echo "  2. Scannez le QR code avec Expo Go"
echo "  3. Connectez-vous avec le code PIN 1234"
echo ""
